### ISSUE TITLE
No dist folder since version 6.0.1

### ISSUE THREAD

**Issue by farnax** [meabed/mongoosastic-ts#283]
Hi there,
for some reason dist folder isn't installed.

## Your Environments

- mongoosastic-ts version: 6.0.2
- node version: 16.18.1
- mongoose version: 6.9.1
- @elastic/elasticsearch: 7.15.0

## Expected Behavior

I expect to see dist folder in node_modules/mongoosastic-ts like with mongoosastic-ts version: 6.0.0

## Actual Behavior

Starts from 6.0.1 mongoosastic-ts version  the Dist folder is missing in the node_modules/mongoosastic-ts directory

![Screenshot](https://user-images.githubusercontent.com/49412363/219348915-deba4f28-e5ad-4a24-8523-5db00072952d.jpg)

## Error Stack

Error: Cannot find module '/backend/node_modules/mongoosastic-ts/dist/mongoosastic.js'. Please verify that the package.json has a valid "main" entry

**Comment by meabed** [comment]
Thanks @farnax i will check and fix in next version

**Comment by meabed** [comment]
Fixed in the latest release 6.0.3 https://www.npmjs.com/package/mongoosastic-ts/v/6.0.3?activeTab=explore
